### ISSUE TITLE
Difficulty Disabling or Using Regex with class-style

### ISSUE THREAD

**Issue by nkoterba** [htmllint/htmllint#211]
Based on the documentation: https://github.com/htmllint/htmllint/wiki/Options#class-style

I've tried setting `class-style` in my `.htmllintrc` config to the various options:
```json
"class-style": "none"
"class-style": ".*"
"class-style": "/.*/"
"class-style": "/.*/g"
```

However, none of these options seems to disable the `class-style` rule.  Instead, I get the following console output:
```javascript
frontend/src/views/menu/menu.template.html
  0:0  warning  unknown  Cannot read property 'test' of undefined
```

If I set the value to: `bem` or remove the property from my config, output seems valid:
```javascript
frontend/src/views/menu/menu.template.html
  3:1    warning  indent-style  Tabs not allowed
  2:3    warning  attr-order    attribute <%= attribute => should come before <%= previous =>
  20:37  warning  class         value must match the format: bem
```

When using `none` or one of the many regex options, it appears the parser or linter is crashing or failing in some ways since I get none of the other output as seen in my second example.

(What's odd too is why are *attribute* and *previous* values in my output the placeholders and not the actual value).

I am running `htmllint` via webpack using `htmllint-loader`.  All of my other htmllint config options seem to work ok.

**Comment by yvanavermaet** [comment]
Seems this is a bug. Tried tracking it and came to a file: lib/knife/get_format_test.js, but I can't find it in the codebase.

@mlochbaum What am I missing here? :)

**Comment by mlochbaum** [comment]
This is fixed in the current htmllint. The reason I haven't released a new version yet is that the new `raw-ignore-regex` option breaks line and column numbers, and I didn't want to release with that bug as it makes the option kind of unusable. I have some time today, so I will try to clear that up and release.

**Comment by srsgores** [comment]
Has this been fixed?  We are looking at using [htmllint-loader](https://github.com/TheBlackBolt/htmllint-loader), and even by specifying the latest `htmllint@0.7.0`, we still get this issue.  We have `"class-style"` set to `"none"`.

**Comment by mlochbaum** [comment]
It works fine for me, and there's a test at the end of `test/functional/class-style.js`. You can check that you're using 0.6.0 instead of 0.7.0 by attempting to set an invalid option like 'abc' to `true`. Version 0.7.0 will report an issue regarding that option and 0.6.0 won't.
